name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source
  contents: read    # to access the repository contents

 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build

    - name: Upload page artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'github-pages'
        path: build 

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact: 'github-pages'